apiVersion: v1
kind: Pod
metadata:
  name: db-pod
spec:
  containers:
  - name: mongo
    image: mongo:latest
    env:
      - name: MONGO_INITDB_ROOT_USERNAME
        value: root
      - name: MONGO_INITDB_ROOT_PASSWORD
        value: example
    ports:
      - containerPort: 27017
        name: mongo