services:
  db:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - db-data:/var/lib/mongoDB

  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - "5000:5000"
    depends_on:
      - db
    environment:
      - MONGODB_URI=${MONGODB_URI}
volumes:
  db-data: