apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ .Release.Name }}-app

spec:
  replicas: 1

  selector:
    matchLabels:
      app: flask-app

  template:
    metadata:
      labels:
        app: flask-app

    spec:
      containers:
        - name: flask
          image: {{ .Values.app.image }}

          ports:
            - containerPort: 5000

          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-db-secret
                  key: uri