apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-secret
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.db.user }}
  password: {{ .Values.db.password }}
  uri: "mongodb://{{ .Values.db.user }}:{{ .Values.db.password }}@{{ .Release.Name }}-{{ .Values.db.name }}:{{ .Values.db.port }}/"