apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: {{ .Release.Name }}-db

spec:
  serviceName: {{ .Release.Name }}-db
  replicas: 1

  selector:
    matchLabels:
      app: {{ .Values.db.name }}

  template:
    metadata:
      labels:
        app: {{ .Values.db.name }}

    spec:
      containers:
        - name: mongo
          image: {{ .Values.db.image }}

          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-db-secret
                  key: username

            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-db-secret
                  key: password

          ports:
            - containerPort: 27017
              name: mongo

          volumeMounts:
            - name: mongo-data
              mountPath: /data/db

  volumeClaimTemplates:
    - metadata:
        name: mongo-data

      spec:
        accessModes:
          - ReadWriteOnce

        storageClassName: gp3

        resources:
          requests:
            storage: 1Gi