api:
  replicas: 2
  name: api
  image: ghcr.io/yunusemretuncer/case_study_hepapi-app
  tag: 428f0b80c874f7875203083a9924e2b94fb7061f
 

db:
  replicas: 1
  name: db
  image: mongo:latest
  port: 27017
  user: root
  password: example
