apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-pod
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      name: app-pod
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: emret7/case_study_hepapi-app
        ports:
        - containerPort: 5000
          name: app
        env:
        - name: MONGODB_URI
          value: "mongodb://root:example@db:27017/"
