apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.api.name }}
spec:
  type: NodePort
  ports:  
  - name: "api-service"
    port: 5000
    targetPort: 5000
    nodePort: 31000
  selector:
    app: {{ .Values.api.name }}