apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-api-deployment
  labels:
    app: {{ .Values.api.name }}
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.api.name }}
  template:
    metadata:
      name: api-pod
      labels:
        app: {{ .Values.api.name }}
    spec:
      containers:
      - name: {{ .Values.api.name }}
        image: "{{ .Values.api.image }}:{{ .Values.api.tag }}"
        ports:
        - containerPort: 5000
          name: {{ .Values.api.name }}
        livenessProbe:
          tcpSocket:
            port: 5000
          initialDelaySeconds: 50
          periodSeconds: 10
        env:
        - name: MONGODB_URI
          valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-db-secret
                key: uri
