apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-db-deployment
  labels:
    app: {{ .Values.db.name }}
spec:
  replicas: {{ .Values.db.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.db.name }}
  template:
    metadata:
      name: db-pod
      labels:
        app: {{ .Values.db.name }}
    spec:
      containers:
      - name: mongo
        image: {{ .Values.db.image }}
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-db-secret
                key: username
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-db-secret
                key: password
        ports:
          - containerPort: 27017
            name: mongo
        volumeMounts:
          - mountPath: "/data/db"
            name: mypd
      volumes:
        - name: mypd
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-myclaim
