apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-secret
type: kubernetes.io/basic-auth
stringData:
  username: root
  password: example 
  uri: "mongodb://root:example@{{ .Release.Name }}-{{ .Values.db.name }}:{{ .Values.db.port }}/"