apiVersion: v1
kind: Pod
metadata:
  name: app-pod
  labels:
    app: app
spec:
  containers:
  - name: app
    image: emret7/case_study_hepapi-app
    ports:
      - containerPort: 5000
        name: app