name: CI

on: push

jobs:
    login:
      runs-on: ubuntu-latest
      permissions:
        packages: write
      services:
        mongodb:
          image: mongo:latest
          ports:
            - 27017:27017
      steps:
        - name: Checkout Repo
          uses: actions/checkout@v6

        - name: Login to Docker Hub
          uses: docker/login-action@v4
          with:
            username: ${{ vars.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}
        

        - name: Login to GHCR
          uses: docker/login-action@v4
          with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Docker Build
          uses: docker/build-push-action@v7
          with:
            context: .
            push: false
            tags: ${{ vars.DOCKERHUB_USERNAME }}/case_study_hepapi-app:${{ github.sha }}
        
        - name: Docker image Testing
          run: |
            docker images
            docker run --name case_study_hepapi-app -d \
              --network host \
              -e MONGODB_URI="mongodb://localhost:27017/TaskManager" \
              ${{ vars.DOCKERHUB_USERNAME }}/case_study_hepapi-app:${{ github.sha }}


            sleep 10
            echo Testing Image URL using wget
            wget -q -O - 127.0.0.1:5000/

        - name: Container Registry Push
          uses: docker/build-push-action@v7
          with:
            context: .
            push: true
            tags: ghcr.io/${{ github.repository_owner }}/case_study_hepapi-app:${{ github.sha }}


          