name: CI

on:
 push:
   branches: ["main"]

jobs:
    unit-testing:
        name: Unit Testing
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
            - uses: actions/checkout@v6

            - name: Setup python
            - uses: actions/checkout@v7

            - name: Install Dependencies
              run: pip install -r requirements.txt
            
            - name: test_script
              run: pytest